# Needed for Metal, the hardware acceleration api for osx
MACOSX_SDK_VERSION:             # [osx]
  - "11.0"                      # [osx]
MACOSX_DEPLOYMENT_TARGET:       # [osx]
  - '10.12'                     # [osx]
c_stdlib:
  - sysroot                     # [linux]
c_stdlib_version:
  - 2.28                        # [linux]
