{% set name = "rerun-sdk" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rerun-io/rerun/archive/refs/tags/{{ version }}.tar.gz
  sha256: 7b893328bb21a143f04bb9ec0dd5154915a9bc0e9b4d86ca8f780a0fa970b82b

build:
  number: 1
  skip: true  # [py<38]
  entry_points:
    - rerun = rerun.__main__:main

requirements:
  build:
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - crossenv                               # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - maturin >=1.3.0                        # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - rust-std-wasm32-unknown-unknown
    # binaryen gives us wasm-opt, for optimizing the an .wasm file for speed and size
    - binaryen
  host:
    - python
    - pip
    - maturin >=1.3.0
  run:
    - python
    - attrs >=23.1.0
    - numpy >=1.23
    - pillow
    - pyarrow >=14.0.2
    - typing_extensions >=4.5
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("11") }}  # [osx]

# TODO(jleibs): Would be nice to add this constraint, but it causes test to fail
# to solve. Just live with the lack of constraint for now.
#
# run_constrained:
#   - __glibc >=2.27                                        # [linux]

test:
  requires:
    - packaging

about:
  home: https://www.rerun.io/
  summary: Rerun is an SDK for logging computer vision and robotics data paired with a visualizer for exploring that data over time.
  description: |
    Rerun is an SDK for logging computer vision and robotics data paired with a visualizer for exploring that data over time. 
    It lets you debug and understand the internal state and data of your systems with minimal code.
  license: MIT OR Apache-2.0
  license_file:
    - THIRDPARTY.yml
    - LICENSE-MIT
    - LICENSE-APACHE

  doc_url: https://www.rerun.io/docs
  dev_url: https://github.com/rerun-io/rerun

extra:
  recipe-maintainers:
    - ruben-arts
    - jleibs
